### ISSUE TITLE
Add localnet as network option

### ISSUE THREAD

**Issue by nxcco** [saifuwallet/saifu#44]
I tried to use Saifu for development using the Solana-test-validator, however I can't, as Saifu only allows to switch between mainnet, devnet and testnet.
I think we should add that localnet option.

**Comment by tengis617** [comment]
@nxcco let us try to get this out in our next release

**Comment by dvcrn** [comment]
We should probably allow adding custom/freeform RPCs as well

**Comment by dvcrn** [comment]
This, together with support for custom RPCs will be out when 1.3 lands, hopefully next week

**Comment by dvcrn** [comment]
This is now released
